#if !canImport(ObjectiveC)
import XCTest

extension HeapTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HeapTests = [
        ("testBuildHeap", testBuildHeap),
        ("testHeap_extract", testHeap_extract),
        ("testHeap_insert", testHeap_insert),
        ("testHeap_pushpop", testHeap_pushpop),
        ("testHeap_replace", testHeap_replace),
        ("testHeapsort", testHeapsort),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(HeapTests.__allTests__HeapTests),
    ]
}
#endif
